version: '3.8'

services:
  ai-teacher:
    container_name: ai-teacher  # Добавьте эту строку
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./materials:/app/materials
    environment:
      - FLASK_ENV=production
      - DEVICE=cpu
    restart: unless-stopped

  nginx:
    container_name: nginx  # Добавьте эту строку
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./static:/app/static
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - ai-teacher
    restart: unless-stopped