version: '3.8'

services:
  ai-teacher:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
      - ./materials:/app/materials
    environment:
      - FLASK_ENV=production
      - DEVICE=cpu
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ai-teacher
    restart: unless-stopped

volumes:
  redis_data:
